project:
  type: book
  output-dir: docs

book:
  title: "Analisi dei dati per psicologi"
  subtitle: "Con applicazioni in Python e R"
  author: "Corrado Caudek"
  date: "22 July 2024"
  search: true
  cover-image: figures/icon_course.jpeg
  repo-url: https://github.com/ccaudek/psicometria/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria/intro.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Python"
      chapters: 
        - chapters/chapter_1/00_prelims.ipynb
        - chapters/chapter_1/01_python_1.ipynb
        - chapters/chapter_1/02_python_2.ipynb
        - chapters/chapter_1/03_numpy.ipynb
        - chapters/chapter_1/04_pandas.ipynb
        - chapters/chapter_1/05_pandas_aggregate.ipynb
        - chapters/chapter_1/06_pandas_functions.ipynb
        - chapters/chapter_1/07_matplotlib.ipynb
        - chapters/chapter_1/08_seaborn.ipynb
    - part: "Fondamenti"
      chapters: 
        - chapters/chapter_2/00_scientific_method.ipynb
        - chapters/chapter_2/01_key_notions.ipynb
        - chapters/chapter_2/02_measurement.ipynb
        - chapters/chapter_2/03_freq_distr.ipynb
        - chapters/chapter_2/04_loc_scale.ipynb
        - chapters/chapter_2/05_correlation.ipynb
        - chapters/chapter_2/06_causality.ipynb
    - part: "Probabilità"
      chapters: 
        - chapters/chapter_3/01_intro_prob.ipynb
        - chapters/chapter_3/02_conditional_prob.ipynb
        - chapters/chapter_3/03_bayes_theorem.ipynb
        - chapters/chapter_3/04a_random_var.ipynb
        - chapters/chapter_3/04b_expval_var.ipynb
        - chapters/chapter_3/04c_sampling_distr.ipynb
        - chapters/chapter_3/05_joint_prob.ipynb
        - chapters/chapter_3/06_density_func.ipynb
        - chapters/chapter_3/07_discr_rv_distr.ipynb
        - chapters/chapter_3/08_cont_rv_distr.ipynb
        - chapters/chapter_3/09_likelihood.ipynb
        - chapters/chapter_3/10_grid_gauss.ipynb
    - part: "Inferenza Bayesiana"
      chapters: 
        - chapters/chapter_4/01_intro_bayes.ipynb
        - chapters/chapter_4/02_subj_prop.ipynb
        - chapters/chapter_4/10_metropolis.ipynb
        - chapters/chapter_4/15_stan_beta_binomial.ipynb
        - chapters/chapter_4/19_stan_odds_ratio.ipynb
        - chapters/chapter_4/22_stan_normal_normal.ipynb
    - part: "Modelli lineari"
      chapters: 
        - chapters/chapter_5/05_03_reglin_bayesian.ipynb
        - chapters/chapter_5/05_04_synt_sugar.ipynb
        - chapters/chapter_5/05_05_two_means.ipynb
  appendices:
    - chapters/chapter_7/a00_installation.ipynb
    - chapters/chapter_7/a01_markdown.ipynb
    - chapters/chapter_7/a02_shell.ipynb
    - chapters/chapter_7/a03_colab_tutorial.ipynb
    - chapters/chapter_7/a04_virtual_env.ipynb
    - chapters/chapter_7/a10_math_symbols.md
    - chapters/chapter_7/a11_numbers.ipynb
    - chapters/chapter_7/a13_sets.ipynb
    - chapters/chapter_7/a13a_probability.ipynb
    - chapters/chapter_7/a14_combinatorics.ipynb
    - chapters/chapter_7/a15_calculus.ipynb
    - chapters/chapter_7/a44_montecarlo.ipynb
    - chapters/chapter_7/a46_stan.ipynb
    - 99-references.qmd

crossref:
  appendix-title: "Online Appendix"

bibliography: ./references.bib

lang: it

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    callout-appearance: simple


