project:
  type: book
  output-dir: docs

book:
  title: "Analisi dei dati per psicologi"
  subtitle: "Con applicazioni in Python e R"
  author: "Corrado Caudek"
  date: "27 Luglio 2024"
  search: true
  cover-image: figures/icon_course.jpeg
  repo-url: https://github.com/ccaudek/psicometria/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria/intro.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd

    - part: "Python"
      chapters: 
        - chapters/chapter_1/introduction_chapter_1.md
        - chapters/chapter_1/00_prelims.ipynb
        - chapters/chapter_1/01_python_1.ipynb
        - chapters/chapter_1/02_python_2.ipynb
        - chapters/chapter_1/03_numpy.ipynb
        - chapters/chapter_1/04_pandas.ipynb
        - chapters/chapter_1/05_pandas_aggregate.ipynb
        - chapters/chapter_1/06_pandas_functions.ipynb
        - chapters/chapter_1/07_matplotlib.ipynb
        - chapters/chapter_1/08_seaborn.ipynb

    - part: "Fondamenti"
      chapters: 
        - chapters/chapter_2/introduction_chapter_2.md
        - chapters/chapter_2/00_scientific_method.ipynb
        - chapters/chapter_2/01_key_notions.ipynb
        - chapters/chapter_2/02_measurement.ipynb
        - chapters/chapter_2/03_freq_distr.ipynb
        - chapters/chapter_2/04_loc_scale.ipynb
        - chapters/chapter_2/05_correlation.ipynb
        - chapters/chapter_2/06_causality.ipynb

    - part: "Probabilità"
      chapters: 
        - chapters/chapter_3/introduction_chapter_3.md
        - chapters/chapter_3/01a_intro_prob.ipynb
        - chapters/chapter_3/01b_prob_spaces.md
        - chapters/chapter_3/01c_prob_on_general_spaces.ipynb
        - chapters/chapter_3/02_conditional_prob.ipynb
        - chapters/chapter_3/03_bayes_theorem.ipynb
        - chapters/chapter_3/04a_random_var.ipynb
        - chapters/chapter_3/04b_expval_var.ipynb
        - chapters/chapter_3/04c_sampling_distr.ipynb
        - chapters/chapter_3/05_joint_prob.ipynb
        - chapters/chapter_3/06_density_func.ipynb
        - chapters/chapter_3/07_discr_rv_distr.ipynb
        - chapters/chapter_3/08_cont_rv_distr.ipynb
        - chapters/chapter_3/09_likelihood.ipynb
        - chapters/chapter_3/10_grid_gauss.ipynb

    - part: "Inferenza Bayesiana"
      chapters: 
        - chapters/chapter_4/introduction_chapter_4.md
        - chapters/chapter_4/01_intro_bayes.ipynb
        - chapters/chapter_4/02_subj_prop.ipynb
        - chapters/chapter_4/03_conjugate_families_1.ipynb
        - chapters/chapter_4/04_conjugate_families_2.ipynb
        - chapters/chapter_4/05_summary_posterior.ipynb
        - chapters/chapter_4/06_balance_prior_post.ipynb
        - chapters/chapter_4/10_metropolis.ipynb
        - chapters/chapter_4/15_stan_beta_binomial.ipynb
        - chapters/chapter_4/16_stan_summary_posterior.ipynb
        - chapters/chapter_4/17_stan_diagnostics.ipynb
        - chapters/chapter_4/18_stan_prediction.ipynb
        - chapters/chapter_4/19_stan_odds_ratio.ipynb
        - chapters/chapter_4/22_stan_normal_normal.ipynb
        - chapters/chapter_4/23_stan_two_groups.ipynb
        - chapters/chapter_4/24_stan_hier_beta_binom.ipynb
        - chapters/chapter_4/25_stan_poisson_model.ipynb
        
    - part: "Modelli lineari"
      chapters: 
        - chapters/chapter_5/introduction_chapter_5.md
        - chapters/chapter_5/05_03_reglin_bayesian.ipynb
        - chapters/chapter_5/05_04_synt_sugar.ipynb
        - chapters/chapter_5/05_05_two_means.ipynb
        - chapters/chapter_5/05_05a_stan_multreg.ipynb
        - chapters/chapter_5/05_06_hier_regr.ipynb
        - chapters/chapter_5/05_07_robust_regr.ipynb
        - chapters/chapter_5/05_08_specification_error.ipynb
        - chapters/chapter_5/05_09_causal_inference.ipynb
        - chapters/chapter_5/05_21_stan_binomial_regr.ipynb
        - chapters/chapter_5/05_22_stan_logistic_regr.ipynb
        - chapters/chapter_5/05_23_stan_poisson_regr.ipynb
        - chapters/chapter_5/05_24_stan_mixed_models.ipynb
        - chapters/chapter_5/05_25_stan_rct.ipynb
        - chapters/chapter_5/05_30_entropy.ipynb
        - chapters/chapter_5/05_31_kl.ipynb
        - chapters/chapter_5/05_32_stan_loo.ipynb
        - chapters/chapter_5/05_35_missing.ipynb
        - chapters/chapter_5/05_40_rescorla_wagner.ipynb

    - part: "Inferenza frequentista"
      chapters: 
        - chapters/chapter_6/introduction_chapter_6.md
        - chapters/chapter_6/01_intro_frequentist.ipynb
        - chapters/chapter_6/02_conf_interv.ipynb
        - chapters/chapter_6/03_test_ipotesi.ipynb
        - chapters/chapter_6/04_two_ind_samples.ipynb
        - chapters/chapter_6/05_crisis.ipynb
        - chapters/chapter_6/06_limits_stat_freq.md
        - chapters/chapter_6/07_effect_size.ipynb
        - chapters/chapter_6/09_s_m_errors.ipynb
        - chapters/chapter_6/10_integrity.ipynb

    - 99-references.qmd

  appendices:
    - chapters/chapter_7/a00_installation.ipynb
    - chapters/chapter_7/a01_markdown.ipynb
    - chapters/chapter_7/a02_shell.ipynb
    - chapters/chapter_7/a03_colab_tutorial.ipynb
    - chapters/chapter_7/a04_virtual_env.ipynb
    - chapters/chapter_7/a10_math_symbols.md
    - chapters/chapter_7/a11_numbers.ipynb
    - chapters/chapter_7/a12_sum_notation.ipynb
    - chapters/chapter_7/a13_sets.ipynb
    - chapters/chapter_7/a14_combinatorics.ipynb
    - chapters/chapter_7/a15_calculus.ipynb
    - chapters/chapter_7/a20_kde_plot.ipynb
    - chapters/chapter_7/a30_prob_tutorial.ipynb
    - chapters/chapter_7/a40_rng.ipynb
    - chapters/chapter_7/a45_mcmc.ipynb
    - chapters/chapter_7/a46_stan.ipynb
    - chapters/chapter_7/a50_lin_fun.ipynb
    - chapters/chapter_7/a51_reglin_1.ipynb
    - chapters/chapter_7/a60_ttest_exercises.ipynb
    - chapters/chapter_7/a70_predict_counts.ipynb
    - chapters/chapter_7/a100_solutions.ipynb

crossref:
  appendix-title: "Appendice"

bibliography: ./references.bib

lang: it

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    callout-appearance: simple
