project:
  type: book
  output-dir: docs

book:
  title: "Analisi dei dati per psicologi"
  subtitle: "Con applicazioni in Python e R"
  author: "Corrado Caudek"
  date: "22 July 2024"
  search: true
  cover-image: figures/icon_course.jpeg
  repo-url: https://github.com/ccaudek/psicometria/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria/intro.html
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - part: "Fondamenti"
      chapters: 
        - chapters/chapter_2/00_scientific_method.ipynb
        - chapters/chapter_2/01_key_notions.ipynb
        - chapters/chapter_2/02_measurement.ipynb
        - chapters/chapter_2/03_freq_distr.ipynb
        - chapters/chapter_2/04_loc_scale.ipynb
        - chapters/chapter_2/05_correlation.ipynb
        - chapters/chapter_2/06_causality.ipynb
    - part: "Inferenza Bayesiana"
      chapters: 
        - chapters/chapter_4/15_stan_beta_binomial.ipynb
  appendices:
    - chapters/chapter_7/a04_virtual_env.ipynb
    - 99-references.qmd

crossref:
  appendix-title: "Online Appendix"

bibliography: ./references.bib

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    callout-appearance: simple
