project:
  type: book
  output-dir: docs

book:
  title: "Data Science per Psicologi"
  
  page-footer:
    left: |
      Data Science per Psicologi è stato scritto da Corrado Caudek.
    right: |
      Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.

  subtitle: "Con applicazioni in Python e R"
  author: "Corrado Caudek"
  date: "2025/3/10"
  search: true
  cover-image: figures/icon_course.jpeg
  repo-url: https://github.com/ccaudek/psicometria/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/psicometria/intro.html
  sidebar:
    collapse-level: 1
    pinned: true
  chapters:
    - index.qmd

    - part: "Python"
      chapters: 
        - chapters/chapter_1/introduction_chapter_1.md
        - chapters/chapter_1/00_prelims.ipynb
        - chapters/chapter_1/01_python_1.ipynb
        - chapters/chapter_1/02_python_2.ipynb
        - chapters/chapter_1/03_numpy.ipynb
        - chapters/chapter_1/04_pandas.ipynb
        - chapters/chapter_1/05_pandas_aggregate.ipynb
        - chapters/chapter_1/06_pandas_functions.ipynb
        - chapters/chapter_1/07_matplotlib.ipynb
        - chapters/chapter_1/08_seaborn.ipynb

    - part: "Fondamenti"
      chapters: 
        - chapters/chapter_2/introduction_chapter_2.md
        - chapters/chapter_2/01_key_notions.ipynb
        - chapters/chapter_2/02_measurement.ipynb
        - chapters/chapter_2/03_data_analysis.ipynb
    - part: "EDA"
      chapters: 
        - chapters/chapter_3/01_project_structure.ipynb
        - chapters/chapter_3/02_freq_distr.ipynb
        - chapters/chapter_3/04_loc_scale.ipynb
        - chapters/chapter_3/05_correlation.ipynb
        - chapters/chapter_3/06_causality.ipynb

    - part: "Probabilità"
      chapters: 
        - chapters/chapter_4/introduction_chapter_3.md
        - chapters/chapter_4/01a_intro_prob.ipynb
        - chapters/chapter_4/01b_prob_spaces.md
        - chapters/chapter_4/01c_prob_on_general_spaces.ipynb
        - chapters/chapter_4/02_conditional_prob.ipynb
        - chapters/chapter_4/03_bayes_theorem.ipynb
        - chapters/chapter_4/04a_random_var.ipynb
        - chapters/chapter_4/04b_expval_var.ipynb
        - chapters/chapter_4/04c_sampling_distr.ipynb
        - chapters/chapter_4/05_joint_prob.ipynb
        - chapters/chapter_4/06_density_func.ipynb
        - chapters/chapter_4/07_discr_rv_distr.ipynb
        - chapters/chapter_4/08_cont_rv_distr.ipynb
        - chapters/chapter_4/09_likelihood.ipynb
        - chapters/chapter_4/10_grid_gauss.ipynb

    - part: "Inferenza bayesiana"
      chapters: 
        - chapters/chapter_5/introduction_chapter_4.md
        - chapters/chapter_5/01_intro_bayes.ipynb
        - chapters/chapter_5/02_subj_prop.ipynb
        - chapters/chapter_5/03_conjugate_families_1.ipynb
        - chapters/chapter_5/04_conjugate_families_2.ipynb
        - chapters/chapter_5/05_summary_posterior.ipynb
        - chapters/chapter_5/06_balance_prior_post.ipynb

    - part: "MCMC"
      chapters: 
        - chapters/chapter_5/10_metropolis.ipynb
        - chapters/chapter_5/15_stan_beta_binomial.ipynb
        - chapters/chapter_5/16_stan_summary_posterior.ipynb
        - chapters/chapter_5/17_stan_diagnostics.ipynb
        - chapters/chapter_5/18_stan_prediction.ipynb
        - chapters/chapter_5/19_stan_odds_ratio.ipynb
        - chapters/chapter_5/22_stan_normal_normal.ipynb
        - chapters/chapter_5/23_stan_two_groups.ipynb
        - chapters/chapter_5/24_stan_hier_beta_binom.ipynb
        - chapters/chapter_5/25_stan_poisson_model.ipynb
        
    - part: "Modelli lineari"
      chapters: 
        - chapters/chapter_6/introduction_chapter_5.md
        - chapters/chapter_6/05_03_reglin_bayesian.ipynb
        - chapters/chapter_6/05_04_synt_sugar.ipynb
        - chapters/chapter_6/05_05_two_means.ipynb
        - chapters/chapter_6/05_05a_stan_multreg.ipynb
        - chapters/chapter_6/05_06_hier_regr.ipynb
        - chapters/chapter_6/05_07_robust_regr.ipynb
        - chapters/chapter_6/05_08_specification_error.ipynb
        - chapters/chapter_6/05_09_causal_inference.ipynb
        - chapters/chapter_6/05_21_stan_binomial_regr.ipynb
        - chapters/chapter_6/05_22_stan_logistic_regr.ipynb
        - chapters/chapter_6/05_23_stan_poisson_regr.ipynb
        - chapters/chapter_6/05_24_stan_mixed_models.ipynb
        - chapters/chapter_6/05_25_stan_rct.ipynb
        - chapters/chapter_6/05_30_entropy.ipynb
        - chapters/chapter_6/05_31_kl.ipynb
        - chapters/chapter_6/05_32_stan_loo.ipynb
        - chapters/chapter_6/05_35_missing.ipynb
        - chapters/chapter_6/05_40_rescorla_wagner.ipynb

    - part: "Inferenza frequentista"
      chapters: 
        - chapters/chapter_7/introduction_chapter_6.md
        - chapters/chapter_7/01_intro_frequentist.ipynb
        - chapters/chapter_7/02_conf_interv.ipynb
        - chapters/chapter_7/03_test_ipotesi.ipynb
        - chapters/chapter_7/04_two_ind_samples.ipynb
        - chapters/chapter_7/05_crisis.ipynb
        - chapters/chapter_7/06_limits_stat_freq.md
        - chapters/chapter_7/07_effect_size.ipynb
        - chapters/chapter_7/09_s_m_errors.ipynb
        - chapters/chapter_7/10_integrity.ipynb

    - 99-references.qmd

  appendices:
    - chapters/chapter_8/a00_installation.ipynb
    - chapters/chapter_8/a01_markdown.ipynb
    - chapters/chapter_8/a02_shell.ipynb
    - chapters/chapter_8/a03_colab_tutorial.ipynb
    - chapters/chapter_8/a04_virtual_env.ipynb
    - chapters/chapter_8/a10_math_symbols.md
    - chapters/chapter_8/a11_numbers.ipynb
    - chapters/chapter_8/a12_sum_notation.ipynb
    - chapters/chapter_8/a13_sets.ipynb
    - chapters/chapter_8/a14_combinatorics.ipynb
    - chapters/chapter_8/a15_calculus.ipynb
    - chapters/chapter_8/a20_kde_plot.ipynb
    - chapters/chapter_8/a30_prob_tutorial.ipynb
    - chapters/chapter_8/a40_rng.ipynb
    - chapters/chapter_8/a45_mcmc.ipynb
    - chapters/chapter_8/a46_stan.ipynb
    - chapters/chapter_8/a50_lin_fun.ipynb
    - chapters/chapter_8/a51_reglin_1.ipynb
    - chapters/chapter_8/a60_ttest_exercises.ipynb
    - chapters/chapter_8/a70_predict_counts.ipynb
    - chapters/chapter_8/a100_solutions.ipynb

crossref:
  appendix-title: "Appendice"

bibliography: ./references.bib

lang: it

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Corrado Caudek"
    callout-appearance: simple

editor: visual

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
