---
title: "Insegnamento capovolto"
date: "Pagina aggiornata il: `r format.Date(file.mtime('index.Rmd'),'%Y-%m-%d')`"
---

## Flip teaching

In questo insegnamento verrà utilizzata la modalità didattica detta _flip teaching_.  La Flipped Classroom prevede due momenti. Nel primo momento, lo studente sarà tenuto a studiare a casa, individualmente e prima della lezione, tutti i materiali assegnati (i materiali didattici saranno disponibili su Moodle). Durante il secondo momento, che comprende le ore svolte in classe, verranno proposte attività di discussione, esercitazione, approfondimento e consolidamento degli argomenti trattati. Ciò consentirà agli studenti, secondo una logica di _learning by doing_, di materializzare, approfondire e sviluppare il processo di apprendimento attivato a casa. Le ore in classe forniranno agli studenti l'opportunità di chiedere chiarimenti, di elaborare i concetti e di partecipare ad esercitazioni mirate ed assistite.

- Agli studenti chiederò di studiare il materiale didattico che verrà assegnato _prima di ciascuna lezione_.

- Agli studenti verrà chiesto di svolgere uno o più esercizi _WarmUp_ _prima di ciascuna lezione_. Ciascun esercizio WarmUp verterà sugli argomenti che verranno trattati a lezione. Gli esercizi esercizio WarmUp consentiranno la preparazione alla discussione in classe e forniranno un feedback sulla comprensione dei contenuti. Ciascun esercizio WarmUp avrà la forma di un Quiz Moodle con domande sia di teoria che di laboratorio pratico sugli argomenti che verranno trattati a lezione. I quiz Moodle rappresentano il livello di difficoltà richiesto per superare l'esame e consentono allo studente di comprendere se le competenze sviluppate fino a quel punto sono sufficienti rispetto alle richieste dell'esame.

- Le lezioni richiederanno la partecipazione attiva degli studenti alla discussione. Vi chiederò di avere sempre a portata di mano un computer poiché spesso svolgeremo insieme esercizi in $\textsf{R}$.

Il programma d'esame è piuttosto esteso: non è possibile concentrare tutta la preparazione e lo studio a ridosso dell'esame. Il modo migliore per prepararsi all'esame è quello descritto sopra: studiare i materiali assegnati _prima_ di ciascuna lezione, svolgere gli esercizi WarmUp assegnati _prima_ di ciascuna lezione, chiedere chiarimenti sul Forum, imparare ad usare $\textsf{R}$ (o Python, se preferite) per applicare i concetti appresi, confrontarsi con gli altri studenti e partecipare in maniera attiva alle lezioni.  

## Esercizi WarmUp

Nella prima parte del semestre (diciamo circa fino alle prima prova parziale) gli esercizi WarmUp saranno simili ai tradizionali problemi scolastici (ovvero richiederanno, per la maggior parte, l'uso di formule per trovare una soluzione). Nella seconda parte del semestre, invece, ci saranno meno esercizi scolastici e l'enfasi si sposterà sulla capacità di applicare le tecniche di analisi dei dati discusse a lezione alla situazione specifica dell'analisi dei dati che dovrà essere svolta nel laboratorio didattico.


