---
engine: knitr
---

## Benvenuti {.unnumbered}

Questo sito web è dedicato al materiale didattico dell'insegnamento di [Psicometria](https://www.unifi.it/index.php?module=ofform2&mode=1&cmd=3&AA=2023&afId=689762) (A.A. 2024/2025), rivolto agli studenti del primo anno del [Corso di Laurea in Scienze e Tecniche Psicologiche](https://www.psicologia.unifi.it/vp-130-scienze-e-tecniche-psicologiche-l-24.html) dell'[Università degli Studi di Firenze](https://www.unifi.it/).

Il corso offre una solida formazione teorica e pratica nell'inferenza statistica, con un'attenzione particolare alle applicazioni nel campo della psicologia. Attraverso esercitazioni pratiche in Python e R, gli studenti acquisiranno le competenze necessarie per manipolare e analizzare dati complessi, e saranno guidati nell’utilizzo di modelli statistici avanzati in un percorso didattico che integra teoria e pratica. 

Il programma copre un ampio ventaglio di argomenti: si parte dalle tecniche fondamentali dell'analisi descrittiva per giungere ai modelli avanzati, come quelli gerarchici e dinamici, con una particolare attenzione all'inferenza causale secondo l’approccio bayesiano. Questo metodo consente di esplorare relazioni causali in modo più sofisticato rispetto ai modelli lineari tradizionali, aprendo la strada a un'analisi più approfondita e accurata dei fenomeni psicologici.

L’obiettivo centrale del corso è introdurre e approfondire l'inferenza bayesiana. Saranno sviluppati i fondamenti metodologici e teorici, insieme alle tecniche computazionali essenziali per la sua applicazione pratica. Verranno esaminati modelli a parametro singolo e multiplo, nonché i principi fondamentali dell’analisi di regressione bayesiana. Le distribuzioni posteriori saranno analizzate mediante avanzati metodi di campionamento Monte Carlo, tra cui le tecniche di Metropolis-Hastings, per promuovere una comprensione pratica e approfondita delle metodologie bayesiane.

### Risultati di apprendimento attesi {.unnumbered}

Al termine del corso, gli studenti saranno in grado di applicare l'inferenza bayesiana, con una solida comprensione del funzionamento dei modelli a parametro singolo e multiplo. Inoltre, avranno sviluppato avanzate competenze computazionali e metodologiche nell’uso di Python e R per la modellazione bayesiana.

Per consolidare le conoscenze acquisite e stimolare la capacità di analisi critica, è stato creato un repository di esercizi, accessibile al seguente [link](https://ccaudek.github.io/psicometria-esercizi/).

## Informazioni sull'insegnamento {.unnumbered}

- **Codice**: B000286 - Psicometria </br>
- **Modulo**: B000286 - Psicometria (Cognomi L-Z) </br>
- **Corso di laurea**: Scienze e Tecniche Psicologiche </br>
- **Anno Accademico**: 2024-2025 </br>
- **Materiali didattici**: È sufficiente disporre di un laptop/computer funzionante. Tutti i materiali didattici e il software necessario sono forniti gratuitamente a tutti gli studenti, senza richiedere alcun acquisto.</br>
- **Calendario**: Il corso si terrà dal 3 marzo al 31 maggio 2025.</br>
- **Orario delle lezioni**: Le lezioni si svolgeranno il lunedì e il martedì dalle 8:30 alle 10:30 e il giovedì dalle 11:30 alle 13:30.</br>
- **Luogo**: Le lezioni si terranno presso il Plesso didattico La Torretta.</br>
- **Modalità di svolgimento della didattica**: Le lezioni ed esercitazioni saranno svolte in modalità frontale.</br>

::: {.callout-note}
Il presente sito web costituisce l'unica fonte ufficiale da consultare per ottenere informazioni sul programma dell'insegnamento B000286 - Psicometria (Cognomi L-Z) A.A. 2024-2025 e sulle modalità d'esame.
:::

## Syllabus {.unnumbered}

Il Syllabus può essere scaricato utilizzando questo [link](syllabus/syllabus.pdf).

\mainmatter
