---
title: "Materiali didattici"
date: "Pagina aggiornata il `r Sys.Date()`"
---

## Dispensa

Tutto ciò che verrà discusso a lezione e che verrà richiesto all'esame è presente nella dispensa 

- [Data science per psicologi](https://github.com/ccaudek/psicometria/blob/main/ds4psy.pdf) 

La dispensa include tutte le istruzioni $\textsf{R}$ per lo svolgimento delle analisi guidate dei dati che sarà necessario conoscere per superare l'esame.

## Materiali supplementari

Il migliore testo introduttivo al linguaggio $\textsf{R}$ è 

- [R for Data Science](https://r4ds.had.co.nz/) 

Per gli scopi dell'insegnamento di Psicometria è sufficiente una conoscenza di base degli argomenti trattati.  

La trattazione dell'inferenza bayesiana fornita nel presente insegnamento segue molto da vicino il modo in cui è stato affrontato questo argomento nei seguenti due testi: 

- [Bayes Rules! An Introduction to Applied Bayesian Modeling]( https://www.bayesrulesbook.com/index.html)
- [Probability and Bayesian Modeling](https://bayesball.github.io/BOOK/probability-a-measurement-of-uncertainty.html)

## Colab

Considerate le difficoltà di alcuni di installare $\mathsf{R}$ e/o `cmdstan` sul proprio computer, una strategia alternativa è quella di usare [colab](https://colab.research.google.com). 

Colab è un servizio gratuito di Google che consente di eseguire codice Python nel browser. In maniera (quasi) del tutto equivalente a RStudio, si può anche eseguire codice $\mathsf{R}$ nel browser. In altri termini, possiamo usare la nostra macchina come un semplice terminale e svolgere tutte le computazioni sui server di Google. In questo modo, se mettiamo a punto uno script che gira su Colab, funzionerà su tutti i computer che si collegano a Colab. 

Il seguente notebook fornisce un tutorial che, include, tra le altre cose, lo svolgimento di un esercizio WarmUp che richiede l'uso di CmdStan:

- [nb_cmdstan.ipynb](https://github.com/ccaudek/psicometria/blob/main/files/nb_cmdstan.ipynb) 

Ricordo che, se usiamo Colab, siamo in un ambiente Python, non in un ambiente $\mathsf{R}$. In altre parole, non stiamo usando RStudio ma bensì un Jupyter Notebook -- un Jupyter Notebook è  simile a RStudio, ma non identico. È un ambiente nel quale possiamo mescolare testo e codice. Alcune celle contengono testo, altre celle contengono codice. Cliccando sull'icona a forma di cerchio che contiene al suo interno un triangolo, posta a sinistra di ciascuna cella, si esegue il codice in quella cella.

Si notino alcune cose.

Per eseguire codice $\mathsf{R}$ dobbiamo prima eseguire `%load_ext rpy2.ipython`. Dopodiché, in una cella di codice, digitiamo la stringa `%%R` seguita dalle istruzioni $\mathsf{R}$. Tutto funziona senza problemi.  $\mathsf{R}$ è già installato.

Se vogliamo usare pacchetti $\mathsf{R}$ diversi da quelli di base, dobbiamo  

- installarli con `install.packages(PACKAGE_NAME)`
- caricarli con `library(PACKAGE_NAME)`

Credo che qualunque cosa venga installata su Colab rimanga attiva, nel nostro account, per 24 ore. Dopodiché viene rimossa. Ciò significa che, in un giorno successivo, dobbiamo nuovamente reinstallare ciò che ci serve. Ciò vale anche per `cmdstan`. L'installazione di `cmdstan` richiede un po' di tempo, circa 3/4 minuti. Tutte le istruzioni per svolgere tali operazioni sono presenti nel tutorial che ho messo a disposizione.

Un'altra cosa da tenere presente è che, in Colab, si possono facilmente leggere file di dati nella memoria di lavoro di $\mathsf{R}$. I file devono essere presenti sul vostro personale Google Drive -- essi non appaiono magicamente: li dovete mettere voi su Drive.  Dovete dunque imparare ad usare Google Drive, ovvero dovete sapere quali cartelle avete creato sul vostro Drive e come salvare i file nelle cartelle. Se volete fare un favore a voi stessi: **NON USATE SPAZI NEI NOMI DELLE CARTELLE E/O DEI FILE**. Se volete usare il tutorial che ho messo a disposizione, dunque, dovete prima mettere il file `kidiq.dta` in qualche cartella del vostro Google Drive. E poi cambiare l'indirizzo che io uso nel tutorial in modo che corrisponda all'indirizzo di quel file sul *vostro* Google Drive. Ovviamente, se volete fare un test, potete usare qualunque altro file.

Vi consiglio di creare una cartella su Google Drive chiamata, ad esempio, `psicometria`. Dentro tale cartella potete creare un'altra cartella chiamata `colab_notebooks`. Nella cartella `colab_notebooks` potete salvare gli script (ora avranno l'estensione `.ipython`). Nella cartella `colab_notebooks` potete creare un'altra cartella, per esempio, `mydata`, in cui salvate i file dei dati. Così sapete dove sono gli script e dove sono i vostri dati su Google Drive.

Dopo avere creato queste cartelle su Google Drive, potete copiare lo script con il tutorial nella cartella `colab_notebooks`. A quel punto, se cliccate (due volte) sull'icona di quel file, il file si attiverà e sarete nell'ambiente di Google Colab. In altre parole, potrete eseguire nel browser il codice contenuto nello script.

Un modo di procedere, per esempio, è quello di copiare il tutorial nella cartella e poi di farne una copia (con un nome diverso, ovviamente) su cui lavorate. Ricordatevi di salvare spesso lo script su cui lavorate. Se spegnete il computer e poi lo riaccendete, il file che avete salvato sarà sempre disponibile su Google Drive.

Nel tutorial ho anche inserito il codice per risolvere un esercizio WarmUp usando Colab, con l'uso di `cmdstan`. Una complicazione è che, per me, è stato più semplice installare in Colab `cmdstanpy`, ovvero la versione di `cmdstan` che fa uso dell'interfaccia Python (non è necessario fare così, ma non sono riuscito ad installare la versione di `cmdstan` che si interfaccia con R).  Ciò significa che le istruzioni che trovate sulla dispensa e nei demo non funzionano pari pari su Colab.  Vanno invece modificate in modo da utilizzare le corrispondenti istruzioni in Python. Nel tutorial trovate quasi tutto quello che vi serve sapere.




