---
title: __Psicometria__
date: today
date-format: "DD MMMM, YYYY"
lang: en-GB
author: 
  - Corrado Caudek
fontfamily: libertine
monofont: inconsolata
monofontoptions: scaled=.95
fontsize: 12pt
spacing: double
geometry: 
  - top=2cm
  - bottom=2cm
  - left=2cm
  - right=2cm
urlcolor: darkblue
linkcolor: Mahogany
citecolor: Mahogany
engine: jupyter
highlight-style: arrow
pdf-engine: pdflatex
format: 
    pdf:
      template: syllabus-template.latex
      toc: true
      toc-depth: 3
      number-sections: false
editor: 
  render-on-save: false
---

# Descrizione sintetica 

Il corso di *Psicometria* (B000286) ha come obiettivo fornire agli studenti le conoscenze fondamentali della Data Science applicate all'analisi di dati psicologici. L'obiettivo è acquisire una solida comprensione dei principi della Data Science, essenziale per progettare studi psicologici validi e interpretare correttamente la letteratura scientifica nel campo della psicologia. Inoltre, le competenze nella Data Science sono ampiamente utilizzate in vari aspetti della pratica psicologica, soprattutto nella costruzione, somministrazione e interpretazione dei test psicometrici. La competenza nella Data Science è, quindi, un elemento fondamentale nella formazione professionale di uno psicologo.

Il corso non si limita a una descrizione teorica degli argomenti, poiché la comprensione di questi concetti richiede l'applicazione pratica in contesti concreti. Pertanto, gli argomenti del corso vengono affiancati da esercitazioni pratiche e laboratori didattici.

Per condurre queste analisi guidate dei dati, sarà necessario utilizzare un computer e un linguaggio di programmazione per l'analisi statistica. In questo insegnamento, il linguaggio Python e il linguaggio di programmazione probabilistico Stan saranno utilizzati per effettuare le analisi statistiche. Grazie all'uso di questi strumenti, gli studenti saranno in grado di applicare in modo pratico i concetti teorici appresi, acquisendo competenze utili per la loro futura carriera professionale come psicologi.

# Obiettivi Formativi

Questo percorso didattico è progettato per introdurre gli studenti alla statistica e alla data science, con un'enfasi particolare sull'analisi e interpretazione critica dei dati psicologici. Il corso è suddiviso in sette moduli principali, ognuno dei quali mira a sviluppare competenze specifiche nei partecipanti:

1. **Introduzione a Python per l'Analisi dei Dati**: Verrà introdotto l'uso di Python, enfatizzando le sue applicazioni nella gestione dei dati, preparando gli studenti all'uso di librerie specifiche per la data science.

2. **Introduzione alla Probabilità**: Questo modulo copre gli elementi fondamentali della teoria della probabilità, inclusa la probabilità condizionata, le distribuzioni di massa e di densità, e le proprietà delle variabili casuali. Gli studenti acquisiranno una solida base teorica necessaria per comprendere metodologie statistiche più avanzate.

3. **Analisi Esplorativa dei Dati (EDA)**: Gli studenti apprenderanno l'importanza dell'EDA per una comprensione accurata dei dati attraverso l'uso di statistiche descrittive fondamentali come media, moda, deviazione standard e intervallo interquartile, e tecniche di visualizzazione quali istogrammi e grafici a dispersione.

4. **Analisi Bayesiana**: Questo modulo introduce l'analisi bayesiana, fondamentale nella modellazione statistica moderna. Attraverso la programmazione probabilistica in Python con Stan, gli studenti svilupperanno la capacità di modellare l'incertezza e aggiornare le inferenze in base a nuove informazioni.

5. **Tecniche Avanzate di Modellazione Statistica**: Gli studenti esploreranno metodi computazionali avanzati come i procedimenti di campionamento e gli algoritmi Markov Chain Monte Carlo (MCMC) per affrontare complessi problemi di inferenza.

6. **Fondamenti di Inferenza Causale**: Saranno trattati i concetti di inferenza causale, fondamentali per costruire modelli che identificano relazioni di causa-effetto oltre la semplice correlazione.

7. **Limiti dell'Inferenza Frequentista**: Una critica ai limiti dell'inferenza frequentista tradizionale, con particolare attenzione ai test dell'ipotesi nulla e agli intervalli di confidenza.

Ogni modulo del corso è strutturato per sviluppare progressivamente le abilità degli studenti in direzione degli obiettivi finali del corso. Questi obiettivi includono lo sviluppo delle capacità necessarie per effettuare inferenze sulla media, confrontare due medie (sia associate che indipendenti), analizzare proporzioni e applicare modelli di regressione, sia bivariati che multipli. Questo approccio progressivo garantisce che gli studenti acquisiscano una comprensione completa e integrata delle tecniche statistiche e delle loro applicazioni pratiche nell'analisi dei dati psicologici.

Con questi obiettivi formativi, il corso intende preparare gli studenti a gestire con competenza le sfide reali nel campo della data science, dotandoli di una robusta base teorica abbinata a solide capacità analitiche pratiche.

# Panoramica del Corso

Questo corso è strutturato per fornire agli studenti una formazione teorica e pratica approfondita nell'inferenza statistica, enfatizzando particolarmente le applicazioni pratiche attraverso la programmazione. Attraverso esercitazioni guidate, gli studenti impareranno a manipolare e analizzare dati psicologici utilizzando Python, acquisendo così le competenze necessarie per prendere decisioni informate e realizzare interpretazioni precise nei loro progetti di modellazione.

Il programma copre un ampio spettro di tecniche, partendo dall'analisi descrittiva per arrivare fino ai modelli gerarchici avanzati. Si pone un forte accento sull'inferenza causale, approcciata da una prospettiva bayesiana, includendo l'uso di Grafi Aciclici Diretti (DAG) per esplorare in modo approfondito le relazioni causali. L'intento è di andare oltre i limiti della modellazione lineare tradizionale, mostrando come integrare efficacemente i modelli psicologici avanzati nell'analisi statistica.

# Filosofia Didattica

In contrasto con gli approcci più tradizionali e teoricamente pesanti comuni nei corsi di analisi dei dati psicologici, il presente insegnamento adotta una filosofia didattica pragmatica e orientata alla pratica. L'obiettivo è superare le convenzioni di focalizzazione esclusiva su teorie e dimostrazioni matematiche per privilegiare l'apprendimento attivo attraverso l'uso di dati reali e strumenti di programmazione avanzati.

Questo approccio permette agli studenti di acquisire competenze pratiche essenziali, enfatizzando l'uso del linguaggio Python anziché l'impiego di formule matematiche complesse. Tale scelta rende il corso più accessibile a studenti con diverse basi di preparazione matematica e promuove una comprensione più profonda dell'interpretazione e dell'applicazione dei risultati statistici.

Python, con la sua crescente popolarità e le sue numerose librerie dedicate all'analisi statistica e alla data science, è stato scelto come strumento principale di questo corso. Utilizzare Python non solo prepara gli studenti all'utilizzo di uno dei linguaggi più richiesti nel campo della ricerca scientifica e dell'analisi dei dati, ma offre anche l'accesso a una vasta gamma di risorse online che possono essere utilizzate per un ulteriore approfondimento.

Inoltre, il corso adotterà un modello didattico di [flipped classroom](https://it.wikipedia.org/wiki/Insegnamento_capovolto), dove gli studenti avranno l'opportunità di esplorare il materiale di studio autonomamente prima delle lezioni in classe. Questo permette di dedicare il tempo in aula a discussioni approfondite, risoluzione di problemi pratici e applicazioni dirette delle tecniche apprese, facilitando un ambiente di apprendimento interattivo e coinvolgente.


# Materiali didattici

Per un'efficace preparazione all'esame, si raccomanda di consultare e studiare in dettaglio i seguenti materiali didattici:

1. [Introduction to Probability](https://www.routledge.com/Introduction-to-Probability-Second-Edition/Blitzstein-Hwang/p/book/9781138369917)
   - Le sezioni specifiche da esaminare sono elencate nel calendario didattico del corso. 
   - È disponibile una versione online gratuita della seconda edizione del libro sul sito [probabilitybook.net](http://probabilitybook.net).

2. [Bayes Rules! An Introduction to Applied Bayesian Modeling](https://www.bayesrulesbook.com/index.html) 
   - Questo testo offre un'introduzione completa alla modellazione Bayesiana applicata.
   - Le sezioni specifiche da esaminare sono elencate nel calendario didattico del corso.

3. Dispensa del corso.
   - La dispensa contenuta in questo sito web fornisce una copertura completa dei temi trattati. Inoltre, include una varietà di esercizi pratici, con istruzioni dettagliate in Python per eseguire le analisi dati rilevanti per l'esame.

4. [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/), i primi due capitoli.
   - I capitoli 1 e 2 sono disponibili gratuitamente seguendo il link fornito.

5. [A Beginners Guide to Python 3 Programming](https://link.springer.com/book/10.1007/978-3-031-35122-8).
   - Il testo di John Hunt fornisce una guida completa per imparare il linguaggio di programmazione Python. Per questo corso, è sufficiente avere una conoscenza di base del linguaggio. È possibile scaricare gratuitamente il testo dal sito Springer utilizzando le credenziali UniFi per l'accesso.
   - [An introduction to Python for R Users](https://rebeccabarter.com/blog/2023-09-11-from_r_to_python#methods) presenta una breve e utile introduzione a Python dal punto di vista della data analisi.

6. Articoli scientifici selezionati.
   - Si richiede un'analisi accurata degli articoli specificati, disponibili nella sezione Moodle del corso.
      - Loken, E., & Gelman, A. (2017). Measurement error and the replication crisis. *Science*, *355*(6325), 584-585.
      - Amrhein, V., Greenland, S., & McShane, B. (2019). Comment: Retire statistical significance. *Nature*, *567*, 305-307.
      - Wasserstein, R. L., Schirm, A. L., & Lazar, N. A. (2019). Moving to a world beyond “p< 0.05”. *The American Statistician*, *73*(sup1), 1-19.

Questi materiali sono essenziali per una comprensione approfondita degli argomenti del corso e per il successo nell'esame finale.

## Materiali supplementari

I seguenti materiali supplementari sono forniti come risorse aggiuntive per coloro che desiderano approfondire gli argomenti trattati nella dispensa o consultare testi che presentano gli stessi contenuti da prospettive diverse.

1. Il libro [An Introduction to Bayesian Data Analysis for Cognitive Science](https://vasishth.github.io/bayescogsci/book/) di Bruno Nicenboim, Daniel Schad, e Shravan Vasishth fornisce un'introduzione alla conduzione dell'analisi dei dati bayesiani e alla modellazione cognitiva utilizzando il linguaggio di programmazione probabilistico Stan. 

2. Il libro [Think Bayes 2](https://allendowney.github.io/ThinkBayes2/) di Allen B. Downey fornisce un'introduzione alla statistica bayesiana usando metodi computazionali (in Python).

3. Il libro [Probability and Bayesian Modeling](https://bayesball.github.io/BOOK/probability-a-measurement-of-uncertainty.html) di Jim Albert e Jingchen Hu fornisce un'ottima introduzione alla statistica bayesiana ed è disponibile online.

4. Il libro [Bayesian Modeling and Computation in Python](https://bayesiancomputationbook.com/welcome.html) presenta discussioni introduttive e avanzate sulla statistica bayesiana usando PyMC. Alcune parti del testo sono disponibili online.

5. Il libro [Bayesian Analysis with Python (3rd ed.)](https://www.packtpub.com/product/bayesian-analysis-with-python-third-edition/9781805127161) di Osvaldo Martin è anch'esso un'ottima introduzione all'inferenza bayesiana con PyMC.

6. Il libro [Data Analysis for Social Science: A Friendly and Practical Introduction](https://press.princeton.edu/books/paperback/9780691199436/data-analysis-for-social-science) scritto da Elena Llaudet e Kosuke Imai (2022) offre un'introduzione accessibile all'analisi dei dati utilizzando il software statistico R. Pur non trattando la statistica bayesiana, il libro rappresenta un'eccellente introduzione agli argomenti trattati nel contesto del presente corso. Si sottolinea che, nonostante gli esempi forniti siano basati su R e non su Python, questa differenza non costituisce una limitazione significativa, poiché con l'assistenza di ChatGPT è possibile agevolmente convertire la sintassi R in Python.

# Guida allo studio

## Metodologia: Flip Teaching

Durante questo corso, adotteremo il metodo del "flip teaching", un approccio pedagogico che favorisce un coinvolgimento attivo e collaborativo nell'apprendimento. Il processo di apprendimento sarà organizzato in due fasi ben distinte: una fase di studio individuale e una di apprendimento collaborativo in classe.

### Studio autonomo

Prima di ogni lezione, vi invito a:

- esaminare accuratamente il materiale didattico assegnato;
- svolgere gli esercizi proposti nella dispensa;
- preparare domande o dubbi da discutere in classe.

Questa fase richiede un impegno individuale significativo per acquisire una comprensione solida dei concetti chiave che saranno poi approfonditi in classe.

### Apprendimento collaborativo in classe

Durante le lezioni in aula, avrete l'opportunità di:

- discutere e chiarire dubbi emergenti dallo studio autonomo;
- partecipare attivamente a discussioni e attività di gruppo;
- collaborare alla risoluzione di problemi pratici, facendo uso del linguaggio Python.

Gli esercizi nella dispensa determinano il livello di preparazione necessario per l'esame; servono come autovalutazione per verificare se avete raggiunto una comprensione adeguata dei concetti trattati.

### Programmazione

Nel contesto dell'analisi dei dati psicologici, la programmazione informatica gioca un ruolo cruciale. Durante il corso, acquisirete le basi di alcuni linguaggi di programmazione essenziali, con un focus particolare sul Python. È fondamentale disporre di un computer per le esercitazioni pratiche.

Vi incoraggio vivamente a sperimentare il [pair programming](https://it.wikipedia.org/wiki/Programmazione_in_coppia) e altre forme di collaborazione come metodi efficaci per affrontare le sfide della programmazione e per facilitare l'apprendimento.

### Comunicare i risultati

Impareremo anche a utilizzare i linguaggi di markup Markdown/HTML e LaTeX per presentare efficacemente i risultati delle analisi statistiche.

### Sviluppo delle abilità

Imparare a programmare richiede pazienza e precisione, in quanto i linguaggi di programmazione operano seguendo regole estremamente letterali. Se da un lato questa peculiarità può generare qualche frustrazione, d'altro canto favorisce lo sviluppo di un approccio algoritmico al pensiero e consente di registrare con rigore e in modo riproducibile ogni fase dell'analisi dei dati. 

Vi consiglio caldamente di utilizzare uno strumento di intelligenza artificiale per supportarvi nello studio e nella pratica della programmazione in Python. Questo vi fornirà un tutor informatico altamente competente sempre a portata di mano. Oltre a mostrare come risolvere un problema, questo tipo di assistente vi spiegherà anche il processo. Il panorama tecnologico cambia in maniera estremamente rapida. Nella mia esperienza, ho constatato che ChatGPT 4.0 (versione a pagamento) rappresenta uno strumento estremamente utile. In passato, si diceva che Google fosse "il migliore amico" di un programmatore. Ora, invece di aprire Google, ci si rivolge direttamente a ChatGPT. 

### Collaborazione e partecipazione attiva

Il corso si propone di promuovere una cultura di apprendimento collaborativo tramite:

- Progetti realistici che incoraggiano la collaborazione e richiedono l'applicazione pratica delle conoscenze acquisite;
- Tecniche collaborative, come il pair programming, che vengono incoraggiate;
- Partecipazione attiva in classe, che include la discussione di argomenti, esempi e quesiti che potrebbero presentarsi negli esami e nei compiti, anche se non sono trattati direttamente nel manuale di riferimento o nelle dispense.

Seguendo queste linee guida, vi preparerete in modo adeguato per affrontare l'esame con competenza e sicurezza. È importante ricordare che non è richiesta alcuna conoscenza pregressa di software specifici o di programmazione informatica — basta avere pazienza e desiderio di imparare.

## AI

L'avvento di linguaggi di programmazione assistiti da intelligenza artificiale, come ChatGPT, Bard, e altri, ha rivoluzionato l'approccio alla programmazione. 

Da una prospettiva didattica, questa evoluzione rappresenta un progresso sostanziale, poiché gli studenti possono beneficiare della guida di un "tutor" sempre disponibile, capace di assistere con precisione anche su questioni tecniche molto specifiche. Pertanto, incoraggio vivamente l'utilizzo di ChatGTP come supporto durante lo studio, sia per l'apprendimento della programmazione in Python sia per la comprensione di concetti teorici più avanzati. 

Tuttavia, ricordate due cose importanti:

- la versione gratuita 3.5 di ChatGPT commette molti errori quando fornisce frammenti di codice;
- durante l'esame non sarà consentito l'uso di alcun sistema di intelligenza artificiale. Questa misura è necessaria per garantire una valutazione equa e basata sulle competenze individuali di ciascuno studente. 

Durante l'esame potrete invece fare riferimento alle vostre note su qualsiasi argomento. Vi consiglio vivamente di adottare questa strategia, che costituisce anche un ottimo modo per studiare. Scegliete il software che meglio si adatta alle vostre esigenze per organizzare le vostre note. Personalmente, trovo molto utile [Obsidian](https://obsidian.md).

## Studenti non frequentanti

Nel quadro di questo insegnamento, voglio sottolineare l'importanza della partecipazione regolare e attiva alle lezioni per massimizzare l'assimilazione dei contenuti e la comprensione dei concetti. Per coloro che non possono partecipare alle lezioni in presenza, l'adozione di un metodo di studio strutturato e metodico risulta fondamentale per prepararsi adeguatamente all'esame finale.

Per massimizzare l'assimilazione del materiale didattico, si consiglia di seguire la seguente strategia:

1. Iniziare leggendo la dispensa relativa al capitolo in esame per ottenere una panoramica essenziale ma dettagliata degli argomenti trattati.
2. Successivamente, dedicarsi all'analisi approfondita del capitolo corrispondente nel libro "Bayes Rules!", per una comprensione più approfondita delle tematiche introdotte.
3. Passare poi allo studio e all'assimilazione del codice Python presentato nelle dimostrazioni pratiche, al fine di integrare la teoria con esempi applicativi.
4. Completare gli esercizi associati a ciascun capitolo per validare la propria competenza tecnica e la comprensione concettuale.
5. Infine, per coloro che desiderano approfondire ulteriormente, i testi opzionali elencati nel Syllabus offrono un'opportunità di esplorare più a fondo ciascun argomento.

Seguendo questa strategia, gli studenti saranno in grado di orientarsi efficacemente attraverso il complesso corpus del materiale didattico e prepararsi al meglio per l'esame finale.

## Forum 

Una risorsa importante, ma spesso sotto-utilizzata, per prepararsi all'esame è il forum dedicato al corso su Moodle. Gli studenti che hanno dubbi dopo aver studiato il materiale assegnato possono porre domande e chiedere chiarimenti utilizzando questo forum.

Partecipare al forum offre vantaggi sia per coloro che chiedono aiuto, sia per coloro che rispondono, poiché spiegare gli argomenti aiuta a consolidare l'apprendimento. È incoraggiato che siano gli stessi studenti a rispondere alle domande degli altri, contribuendo così alla creazione di una comunità di apprendimento collaborativa.

# Procedure di Valutazione dell'Apprendimento

L'esame sarà a libri aperti, consentendo agli studenti di sfruttare qualsiasi risorsa disponibile, sia cartacea che elettronica, sul proprio computer o online. Tuttavia, **sarà strettamente proibito l'utilizzo di strumenti di intelligenza artificiale**. Inoltre, durante la prima e la seconda prova intermedia, sarà richiesto agli studenti di lavorare in modo indipendente, e qualsiasi forma di collaborazione durante l'esame non sarà tollerata.

Le prestazioni degli studenti saranno valutate in modo relativo, in base alla distribuzione delle prestazioni degli studenti che frequentano regolarmente il corso.

Il contenuto dell'esame sarà identico sia per gli studenti frequentanti che per quelli non frequentanti.

## Quiz Moodle

Gli esami per gli studenti frequentanti e le prove in itinere per gli studenti non frequentanti si svolgeranno tramite *quiz Moodle*.

- Ogni quiz Moodle consisterà in domande a scelta multipla, con 5 opzioni di risposta, di cui solo una sarà corretta. Le risposte corrette saranno valutate con un punto, le risposte errate riceveranno una penalizzazione di -0.25 punti e le risposte non date avranno un punteggio di 0.
- Durante il quiz Moodle, gli studenti dovranno rispondere alle domande in ordine sequenziale, senza possibilità di tornare indietro o saltare a domande successive.
- I problemi assegnati a ciascuno studente saranno estratti casualmente da un database, il che comporta variazioni possibili tra gli studenti.
- Durante il quiz Moodle, gli studenti dovranno rispondere sotto pressione temporale.
- Per partecipare ai quiz Moodle, gli studenti dovranno utilizzare il proprio computer.
- I quiz Moodle riguardanti l'inferenza bayesiana richiederanno l'uso di Stan, che dovrà essere installato sul computer dello studente. In alternativa, gli studenti potranno utilizzare Stan su Colab.

## Studenti frequentanti

Per essere considerati "frequentanti", gli studenti devono soddisfare i seguenti requisiti:

1. **Consegna dei report in itinere**: Devono essere consegnati tutti i report in itinere entro le scadenze stabilite, ricevendo un giudizio positivo per ciascuno di essi.
2. **Prove parziali**: È necessario sostenere le due prove parziali programmate durante il semestre.
3. **Progetto di gruppo**: Gli studenti sono tenuti a redigere e consegnare un report scritto, oltre a realizzare una presentazione orale, relativi a un progetto di gruppo focalizzato sull'analisi dei dati di una recente pubblicazione in campo psicologico.

### Dettagli sulle attività e la valutazione

- **Gruppi di lavoro**: Gli studenti verranno suddivisi in piccoli team, ai quali saranno affidate due principali responsabilità:
  1. **Realizzazione di un progetto di gruppo**: il cuore del lavoro sarà la realizzazione di un report che includerà l'analisi approfondita dei dati tratti da una recente pubblicazione  psicologica. Questo progetto, una volta completato e valutato, inciderà sul voto finale di ciascun partecipante.
  2. **Redazione di report in itinere**: al fine di monitorare il progresso del gruppo nel corso del semestre, sarà necessario presentare report periodici che illustrino le attività svolte fino a quel momento. Ogni report dovrà contenere un riassunto delle attività svolte e un'appendice che specifichi i contributi individuali di ciascun membro del gruppo. Questi report saranno valutati secondo un criterio "pass" o "fail".

Gli studenti che riceveranno una valutazione positiva in tutti i report intermedi vedranno il loro voto finale determinato attraverso i seguenti criteri:

- **Valutazione della partecipazione in classe:** Questo aspetto contribuirà con 15 punti su 100 alla valutazione finale. Gli studenti dovranno partecipare all'80% delle lezioni per ottenere questi punti. Il monitoraggio della partecipazione avverrà tramite la funzione *Frequenza Studenti* di Moodle. Gli studenti registreranno la loro presenza accedendo a questo modulo durante l'orario della lezione, utilizzando la password fornita in aula di volta in volta.
- **Primo esame parziale:** Il primo quiz parziale (svolto su Moodle) a metà corso concorrerà per 25 punti nel calcolo del voto finale.
- **Secondo esame parziale:** Il secondo quiz parziale (sempre su Moodle) alla fine del corso sarà valutato fino a 30 punti per il voto finale.
- **Progetto di gruppo:** La valutazione del progetto di gruppo contribuirà con 30 punti al voto finale. Tale valutazione si baserà sulla presentazione scritta e orale di un'analisi dati relativa ad una recente pubblicazione in campo psicologico.
- **Voto finale**: Il voto finale sarà valutato su un totale di 100 punti, successivamente convertiti in un voto in trentesimi basato sulla distribuzione dei punteggi di tutti gli studenti.

### Esperienza di laboratorio

- **Bonus**: Gli studenti hanno l'opzione di guadagnare 2 punti bonus partecipando a un'esperienza di laboratorio (impegno di circa 5 ore). Questi punti saranno sommati al voto finale in trentesimi.

- **Codice**: Per iscriversi all'esperienza di laboratorio, usare il seguente codice (da aggiungere al modulo di iscrizione ai gruppi):

  - Prime due lettere del nome,
  - Prime due lettere del cognome,
  - Data di nascita: anno, mese, giorno, es, 1999_03_06 (6 marzo 1999),
  - Ultime 3 cifre del cellulare,
  - Genere.
  - Separatore: trattino basso.

  - Per esempio: Mario Rossi, nato il 6 marzo 1999, telefono 320 2294312.
    Codice: ma_ro_1999_03_06_312_m

- Nonostante non sia obbligatoria, l'esperienza di laboratorio offre l'opportunità di aumentare il punteggio e acquisire una visione pratica dei progetti di ricerca in psicologia. 
  - Si noti che, durante questo laboratorio, si adotteranno tecniche di analisi statistica per identificare comportamenti inappropriati come il "careless responding". In caso di comportamenti scorretti, gli studenti perderanno l'opportunità di guadagnare punti bonus e saranno sottoposti a un'integrazione orale obbligatoria per superare l'esame.


### Considerazioni aggiuntive

- **Storico**: Negli anni accademici passati, la maggior parte degli studenti ha optato per il percorso "frequentanti", conseguendo risultati positivi.

Gli studenti sono incoraggiati a sfruttare questo percorso per ottenere una formazione pratica approfondita e un voto finale soddisfacente.

Gli studenti frequentanti che supereranno l'esame **dovranno** iscriversi al primo appello utile d'esame. Una volta iscritti, non dovranno compiere ulteriori azioni poiché mi occuperò personalmente della verbalizzazione e dell'inserimento del voto.

## Studenti non frequentanti

L'esame per le sessioni degli esami sarà condotto tramite un quiz Moodle, simile agli esercizi presenti nella dispensa.

Affinché gli studenti possano partecipare all'esame, è necessario che portino con sé un computer portatile alla Torretta il giorno previsto per l'esame, come è richiesto anche per gli studenti che frequentano regolarmente le lezioni.

Desidero sottolineare che il programma d'esame rimarrà invariato e sarà applicato uniformemente sia agli studenti frequentanti che a quelli non frequentanti.

# Ulteriori informazioni

## Ricevimento

Avendo diversi insegnamenti la stessa giornata, lascerò l'aula immediatamente dopo la fine della lezione. Resto comunque a vostra disposizione e sono facilmente raggiungibile tramite Moodle. Essendo un docente con un alto numero di studenti, vi chiedo cortesemente di evitare di contattarmi via e-mail e di utilizzare invece Moodle per organizzare eventuali incontri di gruppo. Durante queste occasioni, potremo interagire in modo tranquillo e produttivo attraverso Google Meet. Questo ci consentirà di rispondere alle vostre domande e fornire ulteriori chiarimenti in modo efficace e organizzato, rispettando nel contempo le misure di sicurezza in vigore.

## Comportamento in aula

Nel contesto di questo corso, attribuiamo un'importanza cruciale alla considerazione reciproca. Invito calorosamente tutti gli studenti a partecipare attivamente alle discussioni in aula, poiché ciascuno di voi potrebbe avere opinioni diverse sugli argomenti trattati. L'apporto di prospettive differenti non solo è gradito, ma anche estremamente apprezzato, poiché arricchisce il dibattito e favorisce una comprensione più completa e diversificata delle tematiche in esame.

Inoltre, è altrettanto importante mettere in discussione le idee degli altri, comprese le mie. Tuttavia, per garantire che le discussioni siano proficue, mi impegno a svolgere il ruolo di moderatore, assicurando che le idee vengano esaminate in modo tranquillo e rispettoso, e che gli argomenti vengano esposti in modo chiaro e logico.

La partecipazione attiva e il rispetto reciproco durante le discussioni contribuiranno a creare un ambiente accademico stimolante e arricchente, che favorirà il vostro apprendimento e la crescita intellettuale. Pertanto, vi incoraggio vivamente a prendere parte attiva alle lezioni e a condividere il vostro punto di vista, contribuendo così a arricchire l'esperienza di tutti i partecipanti.

## Norme relative all'uso della posta elettronica

Desidero sottolineare l'importanza di un utilizzo diligente della posta elettronica nel contesto del nostro corso. Di solito, mi impegno a rispondere prontamente alle e-mail degli studenti, ma vorrei porre l'accento su alcune considerazioni per ottimizzare questa forma di comunicazione.

Innanzitutto, vorrei gentilmente richiamare la vostra attenzione sul fatto che molte delle informazioni che potreste cercare sono già disponibili sul sito web del corso. Prima di inviarmi una richiesta, vi prego di *consultare attentamente il materiale fornito sul sito web*. Questo eviterà duplicazioni e permetterà una gestione più efficiente delle comunicazioni.

Per agevolare ulteriormente la vostra interazione con me, desidero ribadire alcuni punti cruciali:

1. Il programma d'esame, le modalità di svolgimento dell'esame e i testi consigliati per la preparazione degli studenti non frequentanti sono disponibili sul sito web del corso.
2. Per organizzare un incontro tramite Google Meet, vi invito a inviarmi un messaggio personale attraverso Moodle, che sarà uno strumento di gestione organizzativa delle riunioni. Preferisco, ove possibile, pianificare incontri di gruppo, ma qualora fosse necessario un colloquio individuale, potremo concordare un appuntamento "privato".

Adottando queste pratiche, renderemo la nostra comunicazione più fluida ed efficiente, consentendoci di concentrarci maggiormente sul vostro apprendimento e sulla massimizzazione dei risultati durante le attività didattiche.

## Politica sulla disonestà accademica

L'integrità accademica rappresenta un principio fondamentale per garantire un corretto svolgimento del percorso formativo. Pertanto, desidero enfatizzare la disapprovazione di qualsiasi forma di comportamento disonesto. Vi esorto dunque ad astenervi dal:

1. Utilizzare aiuti non autorizzati durante test in classe o nell'esame finale;
2. Copiare, sia intenzionalmente che involontariamente, testo, struttura o idee da fonti esterne senza attribuire correttamente la fonte.

La disonestà accademica non solo viola principi etici fondamentali, ma mina anche la credibilità e l'equità del processo di valutazione e dell'apprendimento stesso. Per questo motivo, mi impegno a far rispettare rigorosamente la politica accademica in vigore, che prevede misure adeguate in caso di violazioni.

Nel perseguire la formazione accademica, è essenziale instaurare una cultura di onestà e rispetto delle regole, al fine di garantire un ambiente di apprendimento etico e proficuo per tutti i partecipanti. Sono fiducioso nel vostro impegno a mantenere un comportamento corretto e rispettoso degli standard di integrità accademica richiesti.

## Politica sulle disabilità

Nel caso in cui uno studente presenti bisogni educativi speciali, lo invito a comunicarmelo *in modo confidenziale* quanto prima. Assicuro il pieno rispetto del diritto alla privacy in materia, senza alcuna eccezione.

## Considerazioni finali

Come avviene in ogni corso, il successo degli studenti è principalmente determinato dal loro impegno durante il semestre. È essenziale chiedere aiuto ai compagni di classe e a me: non esitate a porre domande su ciò che non avete compreso o a verificare la vostra comprensione di un argomento.

